### ISSUE TITLE
AR Create. CC field does not auto complete

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.lims#29]
## Steps to reproduce
Create AR for Contact that has colleagues configured to be auto cc'd the COA at publication

## Current behavior

selecting the Contact on AR Create, should see the CC contacts filed autocomplete from the principa contacts publication preferences configuration

![image](https://user-images.githubusercontent.com/1196034/34253507-97030248-e650-11e7-8a30-e64b9f0ccd0f.png)

## Expected behavior

AR Create form's CC Contacts fileld should auto complete from the the main Contact's preferences

**Comment by lemoene** [comment]
this cost the user a few clicks

**Comment by ramonski** [comment]
Will be tracked in https://github.com/senaite/bika.lims/issues/491
