### ISSUE TITLE
Reject CSS is no loaded

### ISSUE THREAD

**Issue by Espurna** [senaite/senaite.lims#31]
## Steps to reproduce

1- Activate and create rejection options in bika setup.
2- Create an analysis request
3- Reject the sample or analysis request

## Current behavior

When clicking on the "reject" transition option, the JS logic defined for rejection works, but the CSS doesn't.

## Expected behavior

An overlay should block the whole page, have a look at the attached images.

## Screenshot (optional)

How it works in bika.lims and how it should work:

![selection_037](https://user-images.githubusercontent.com/7425587/34297881-f889cc84-e71a-11e7-8b66-0f334a7c1162.png)

How it works in senaite.lims:

![selection_036](https://user-images.githubusercontent.com/7425587/34297539-f0b231c4-e718-11e7-8602-eaae1e7e1987.png)

**Comment by ramonski** [comment]
Fixed in Core: https://github.com/senaite/senaite.core/pull/1309
