### ISSUE TITLE
Individual AS prices on AR Create form

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.lims#37]
Quoting is a popular topic among commercial labs, the pricing on ARs satisfies half of them

not urgent

## Steps to reproduce

Create new ARs

## Current behavior

![image](https://user-images.githubusercontent.com/1196034/34320927-06de41f6-e80c-11e7-8cbe-ca239b43873f.png)

## Expected behavior

Individual Analysis prices to be listed too

**Comment by ramonski** [comment]
This would have an performance impact. The prices are fetched by clicking on the info icon of a service

**Comment by lemoene** [comment]
Only for Client logons?

**Comment by ramonski** [comment]
<img width="646" alt="happy_hills_ _senaite" src="https://user-images.githubusercontent.com/713193/34434404-402e6be2-ec86-11e7-9137-ed051a8f3339.png">
