### ISSUE TITLE
AR Create. 'All' Contacts briefly displayed 

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.lims#40]
https://github.com/senaite/bika.lims/pull/492 works nicely thanks

I noticed something earlier that could hint at a bug in the AR Create UI, I managed to capture for the first time now.

## Steps to reproduce

Create a new AR, complete the Primary Contact field, then click in the CC Contacts field

## Current behavior

The pop-up briefly displays all Client Contacts, before filtering them correctly

![image](https://user-images.githubusercontent.com/1196034/34354946-9def9b64-ea3a-11e7-963c-1ffe6e45e92e.png)

![image](https://user-images.githubusercontent.com/1196034/34355028-278ae07c-ea3b-11e7-95ca-71639e3d5bd4.png)

probably nothing to do with it, this Client only has one Contact. It is still up for selection, the selected primary Contact not on the selection list is a nice cosmetic to give to a student later

## Expected behavior

Only the Client's own Contacts should be up for selection (and in de lux, excluding the selected Primary Contact). And the All Contacts list not displayed, also as a matter of privacy where they do their own AR creation

**Comment by ramonski** [comment]
Thanks for the hint, I'm aware of this issue.

However, although it might seem like a "cosmetic student task", it involves a complete re-design of the reference widget, which needs a rework of the complete AR Add view as well as all fields in the LIMS where the reference widget is used.

Please avoid therefore any categorization of issues regarding their needed efforts, which might be misleading to others.

Thanks for understanding.
