### ISSUE TITLE
Backend fetch errors

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.lims#41]
You'll probably pick this up in Sentry ( still wish for the error log to be available to lanmanagers:-) but i often get  

_Error 503 Backend fetch failed. Backend fetch failed. Guru Meditation: XID: 1867980. Varnish cache server_

## Steps to reproduce

In this case during _Cancelling_ 30 odd ARs, error is produced at /analysisrequests/workflow_action. The actual cancellations did take place.

## Current behavior

503s

## Expected behavior

Should execute the transitions without errors

**Comment by ramonski** [comment]
This is a timeout setting of Varnish and should be individually set on the client's machine.
