### ISSUE TITLE
Default description field tag font, text edit box sizes

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.lims#50]
With the hope that this can be easily sorted centrally now

## Steps to reproduce

Open any setup item that include  long field tags and edit boxes, e.g. /bika_setup/bika_analysisspecs/analysisspec-14

## Current behavior

All description texts are Bold and the text boxes unnecessarily narrow and deep, making for too much scrolling

![image](https://user-images.githubusercontent.com/1196034/34452562-f7301ca4-ed4a-11e7-9593-906ecdcd7875.png)

![image](https://user-images.githubusercontent.com/1196034/34453555-913febfc-ed60-11e7-9fe0-c971c6429233.png)

## Expected behavior
Form will be easier to consume if the description fields are not Bold, the grey is cool.

Text entry boxes should open more economically, full width, and empty ones no more than 2 lines deep.

![image](https://user-images.githubusercontent.com/1196034/34452579-47e5d580-ed4b-11e7-889b-75297bcb696c.png)

Specs

![image](https://user-images.githubusercontent.com/1196034/34453566-b5ab9c20-ed60-11e7-9970-6887f51dacfb.png)

**Comment by ramonski** [comment]
Please note that although we appreciate any kind of improvement request, we can't keep track of them in this tracker and would therefore encourage you to open a Pull Request directly and we'll be happy to give our feedback and eventually merge it into master.
Thanks for understanding.
