### ISSUE TITLE
AR Create. The Sample row should be above the fields depending on its selection

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.lims#52]
## Steps to reproduce

Create a secondary AR on a previously received Sample

## Current behavior

The _Sample_ filed for selecting the existing Sample, is near the bottom of the header section, while the fields referenced from it and auto completed on its selection, are unconventionally spaced above it, sometimes making for unnecessary scrolling

![image](https://user-images.githubusercontent.com/1196034/34457225-2f61bc32-edb3-11e7-9113-05ca5997af4a.png)

## Expected behavior

Will be smoother with the Sample row above the first of its dependencies as annotated above

**Comment by ramonski** [comment]
The order can be set via drag&drop in the "Manage Form Fields" View

<img width="1567" alt="happy_hills_ _senaite" src="https://user-images.githubusercontent.com/713193/34457336-3617fc4e-edae-11e7-872d-fe212e14b12e.png">
