### ISSUE TITLE
AR templates list unsorted

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.lims#53]
## Steps to reproduce

navigate to AR Templates in the Bika Setup

## Current behavior

The default list is not sorted alphabetically

![image](https://user-images.githubusercontent.com/1196034/34460345-0b034886-ee14-11e7-81f1-c94bc0637001.png)

## Expected behavior

The default list to be sorted alphabetically

**Comment by ramonski** [comment]
Tracked in `senaite.core` – closing
