### ISSUE TITLE
Some TinyMCE functionality seems to be disabled

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.lims#59]
Standard Plone 'Document Management' is required by labs who use it for say Accreditation documentation.

I am not sure which html get stripped, there seems to be no padding on pages. Most notably all tables get converted to Plain

## Steps to reproduce

Create a new page say at / as admin. Insert a table class _Invisible grid_. 

![image](https://user-images.githubusercontent.com/1196034/35147948-2b181e94-fd19-11e7-8265-c898f5f2abf0.png)

![image](https://user-images.githubusercontent.com/1196034/35148009-4bcc5ee8-fd19-11e7-9b37-e6284f279759.png)

When the page is saved, the table converts to _Plain_

I went through the Plone setting in setup without picking up whether this is a configuration issue only

## Current behavior

After saving and re-opening the page, the table is converted to plain. Very iffy behaviour, seems empty tables are not saved at all

**Comment by lemoene** [comment]
cannot reproduce the bit where it resets to _Plain_. _Fancy listing_  saves as class _Listing, and_ _Subdued_ saves as class _Plain_

Both seem to render as Fancy

![image](https://user-images.githubusercontent.com/1196034/35148511-248eb860-fd1b-11e7-9851-7080c05e935e.png)

**Comment by lemoene** [comment]
Images cannot be right or left alligned anymore

**Comment by ramonski** [comment]
Fixed in https://github.com/senaite/senaite.lims/pull/96
