### ISSUE TITLE
Couldn't find index page for 'senaite.lims' (maybe misspelled?)

### ISSUE THREAD

**Issue by phillip-toone** [senaite/senaite.lims#60]
I attempt to install senaite.lims according to the instruction provided in the README.md as follows:

```
apt update
apt install -y python-setuptools python-dev build-essential libssl-dev libxml2-dev libxslt1-dev libbz2-dev libjpeg62-dev libz-dev
apt install -y libreadline-dev wv poppler-utils
apt install -y git
wget --no-check-certificate https://launchpad.net/plone/4.3/4.3.6/+download/Plone-4.3.6-UnifiedInstaller.tgz
tar -xf Plone-4.3.6-UnifiedInstaller.tgz
cd Plone-4.3.6-UnifiedInstaller
./install.sh standalone
```
This generates the expected "Installation Complete" output along with the username and password but when I proceed to add senaite.lims to the eggs list with nano and run the buildout as follows:
```
cd /usr/local/Plone/zinstance
nano buildout.cfg
sudo -u plone_buildout bin/buildout
```
I get the following output and associated error message:
```
Uninstalling precompiler.
Uninstalling zopepy.
Uninstalling instance.
Installing instance.
Couldn't find index page for 'senaite.lims' (maybe misspelled?)
Getting distribution for 'senaite.lims'.
Couldn't find index page for 'senaite.lims' (maybe misspelled?)
While:
  Installing instance.
  Getting distribution for 'senaite.lims'.
Error: Couldn't find a distribution for 'senaite.lims'.
```

**Comment by xispa** [comment]
First, install Plone 4.3.15 rather than 4.3.6. The latter is too old and we cannot guarantee the system will work. Apart from this, I'd say that just adding an `index=https://pypi.python.org/simple` inside the `buildout` section of your `buildout.cfg` should be enough to fix your installation problem:

```
[buildout]
index = https://pypi.python.org/simple
```
More info here: https://community.plone.org/t/buildout-not-working-couldnt-find-index-page-for-couldnt-find-a-distribution-disabling-non-https-access-to-apis-on-pypi/5069

Please confirm if it works as expected after applying these changes.

Thanks for reporting, we'll update README.rst accordingly asap.

**Comment by phillip-toone** [comment]
Thank you. That seemed to fix that problem but now I get the following output from the attempted buildout.
```
Getting distribution for 'cairocffi'.
c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
An error occurred when trying to install cairocffi 0.8.0. Look above this message for any errors that were output by easy_install.
While:
  Installing instance.
  Getting distribution for 'cairocffi'.
Error: Couldn't install: cairocffi 0.8.0
```
In addition I get lots for warnings and this error repeated multiple times:
```
SyntaxError: 'return' outside function
```
Let me know if you would like to see the entire output of the buildout or if what I have included is sufficient for you to understand what the problem is.

**Comment by phillip-toone** [comment]
I've discovered that this error is remedied by installing libcairo2.  For reference here is a complete list of the dependencies required by Ubuntu 16.04.
```
apt install -y python-setuptools libxml2-dev libxslt1-dev libbz2-dev libjpeg62-dev libz-dev
apt install -y libreadline-dev wv poppler-utils git
apt install -y build-essential gcc python-dev git-core libffi-dev
apt install -y libpcre3 libpcre3-dev autoconf libtool pkg-config
apt install -y zlib1g-dev libssl-dev libexpat1-dev libxslt1.1
apt install -y gnuplot libcairo2 libpango1.0-0 libgdk-pixbuf2.0-0
```

**Comment by Jimbou** [comment]
I'm using Plone-4.3.18 and successfully run senaite.lims with this buildout file.
I can activate (`bin/instance fg`) and access the LIMS website. 

```
[buildout]
parts =
    instance

extends = http://dist.plone.org/release/4.3.18/versions.cfg
index = https://pypi.python.org/simple/

find-links =
    http://dist.plone.org/release/4.3.18
    http://dist.plone.org/thirdparty
   
[instance]
recipe = plone.recipe.zope2instance
user = admin:admin
eggs =
    Plone
    Pillow
    senaite.core
    senaite.core.supermodel
    senaite.lims


[versions]
Products.AdvancedQuery =< 4
```

But, when I'm adding `senaite.instruments` to the eggs a similar error occurs

```
> /home/roman/Plone/senaite.lims/eggs/setuptools-26.1.1-py2.7.egg/pkg_resources/__init__.py:188: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
>   stacklevel=1,
> Couldn't find index page for 'senaite.instruments' (maybe misspelled?)
```

**Comment by ramonski** [comment]
Hi @Jimbou, senaite.instruments isn‘t officially released yet, hence the error message.
You need to add the sources if you want to use it for now.

**Comment by scmos** [comment]
> Hi @Jimbou, senaite.instruments isn‘t officially released yet, hence the error message.
> You need to add the sources if you want to use it for now.

How can I change sources to use alternative code? Please help.
