### ISSUE TITLE
Work space reduced significantly in 15inch screens

### ISSUE THREAD

**Issue by xispa** [senaite/senaite.lims#61]
## Steps to reproduce

Create a new Analysis Request

## Current behavior

On creating any object, the system gives an informational alert that the object has been successfully created. The alert is big and visible which is good. However, it now expects a user to manually close it, which may introduce more clicks for the users.

Given that the elements have generally moved down, the work space has reduced significantly. On an 15 inch screen, one can only be able to see 6 requests with the alert displayed. See image attached.

## Expected behavior

The workspace is not reduced significantly

## Screenshot (optional)

![selection_050](https://user-images.githubusercontent.com/832627/37278400-df4ae026-25e7-11e8-9f96-b79ba92fe434.png)

**Comment by ramonski** [comment]
Is this better now w/o the global sections navigation?
