### ISSUE TITLE
Errors while installing.

### ISSUE THREAD

**Issue by devlinpadayachee** [senaite/senaite.lims#64]
## Steps to reproduce
Install on Ubuntu 17

## Current behavior
Getting distribution for 'WeasyPrint==0.42'.
error: Setup script exited with error in WeasyPrint setup command: Invalid environment marker: python_version < "3.0"
An error occurred when trying to install WeasyPrint 0.42. Look above this message for any errors that were output by easy_install.
While:
  Installing client1.
  Getting distribution for 'WeasyPrint==0.42'.
Error: Couldn't install: WeasyPrint 0.42

## Expected behavior
Clean install

**Comment by ramonski** [comment]
Duplicate of https://github.com/senaite/senaite.core/issues/560

**Comment by devlinpadayachee** [comment]
Thanks Sir I actually got it working
