### ISSUE TITLE
Users have access to "content action menu" for some "folder" objects

### ISSUE THREAD

**Issue by Espurna** [senaite/senaite.lims#65]
## Steps to reproduce

Go to analysis services folder, click on actions drop-down and select "delete". If no dependencies are associated to those objects, the whole Folder will be deleted.

It happens on most of "folder" objects.

Something similar was fixed here: https://github.com/senaite/senaite.core/pull/636

Could this be the reason that this doesn't happen to some Folders? https://github.com/senaite/senaite.core/blob/master/bika/lims/browser/clientfolder.py#L56

## Current behavior

Users can delete, change the state, etc of "folder" objects such as Analysis Services view, Methods, etc

Please, note that this doesn't happen for some objects such as Clients view and  Reference Samples

## Expected behavior

Those objects should NEVER appear

## Screenshot (optional)
The potential problem:

![selection_005](https://user-images.githubusercontent.com/7425587/38946440-bf7c5b02-4339-11e8-8b3f-161d0b240c7a.png)
![selection_004](https://user-images.githubusercontent.com/7425587/38946442-bf976230-4339-11e8-9b26-72944fc5d875.png)

The problem itself:

![selection_006](https://user-images.githubusercontent.com/7425587/38946525-fbd103c8-4339-11e8-960d-fb201e7b05db.png)

**Comment by ramonski** [comment]
Hi @Espurna, this is related to https://github.com/bikalims/bika.lims/pull/1920.
The reason why these objects from the setup are accessible by anonymous is because anonymous uses should see the accreditation portlet (uses AccreditationBodyLogo etc.), the Methods and some other stuff.

However, you're right and this should not be.
IMO users that are not authenticated should see nothing...

**Comment by Espurna** [comment]
Hi @ramonski , thank you for your prompt response.
They aren't anonymous users, the problem I have reported stands that users can delete folders like "Methods". in my opinion no one should be able to delete the Clients folder neither "Methods".

**Comment by xispa** [comment]
Ugly things that come from the old days:
https://github.com/senaite/senaite.core/blob/master/bika/lims/profiles/default/cssregistry.xml#L6
