### ISSUE TITLE
My Senaite site is in portuguese!?

### ISSUE THREAD

**Issue by phillip-toone** [senaite/senaite.lims#93]
I set up a Senaite site to use for evaluation purposes.  But now the site is in Portuguese.  I don't know how this happened but I would really appreciate some help getting it back to English.

(I only know it is in Portuguese because I used google translate on the phrase "Pedidos de análise".)

**Comment by ramonski** [comment]
Hi @phillip-toone,
there must be a language selector in the upper right corner to switch back to english:

<img width="1192" alt="senaite 2019-01-30 22-50-48" src="https://user-images.githubusercontent.com/713193/52015152-9fdfda00-24e1-11e9-814f-4b74cfb12412.png">

The available languages can be set via the ZMI language tool:

<img width="1192" alt="senaite 2019-01-30 22-53-00" src="https://user-images.githubusercontent.com/713193/52015273-eaf9ed00-24e1-11e9-958c-06a7dcfe4d84.png">

**Comment by phillip-toone** [comment]
The second method worked for me. Thank you.
