### ISSUE TITLE
Unable to install because of problem with python dependency cairocffi

### ISSUE THREAD

**Issue by simernes** [senaite/senaite.lims#98]
Hi, I've tried to follow the steps to install on both Fedora 29 and Ubuntu 18.04 but I end up with this issue caused by cairocffi:

## Steps to reproduce
1. Install https://launchpad.net/plone/4.3/4.3.18/+download/Plone-4.3.18-UnifiedInstaller.tgz on Ubuntu 18.04 with sudo, by running install.sh standalone
2. Add senaite.lims to buildouts.cfg
3. run buildout with sudo -u plone_buildout bin/buildout

## Current behavior
Crashes with following error:
> File "/tmp/easy_install-Qi9WsC/cairocffi-1.0.2/setup.py", line 7, in <module>
RuntimeError: cairocffi does not support Python 2.x anymore. Please use Python 3 or install an older version of cairocffi.
An error occurred when trying to install cairocffi 1.0.2. Look above this message for any errors that were output by easy_install.
While:
  Installing instance.
  Getting distribution for 'cairocffi'.
Error: Couldn't install: cairocffi 1.0.2

## Expected behavior
Install normally

If I run pip install cairocffi as a regular user with python 2.7, it install cairocffi 0.9.0, would there perhaps be a way to specify that version so it doesn't try to pull in 1.0.2 which isn't supported anymore? Any other suggestions are also welcomed!

**Comment by simernes** [comment]
Managed to get past it by adding the following to versions in buildout.cfg:
cairocffi = 0.9.0
tinycss2 = 0.6.1

**Comment by ramonski** [comment]
Hi @simernes,
thanks for providing directly the solution to your opened issue. Please note, that we already addressed that version pinning in the current `master` branch of `senaite.core`:
https://github.com/senaite/senaite.core/blob/master/setup.py#L61
Therefore, it should work w/o issues when we release the upcoming 1.3 version.

Anyhow, please consider adding these hints also on our community site: https://community.senaite.org
